2023-06-27 21:04:16,682  - INFO - Log file log/27-Jun-23_21:04:16.log successfully created.
2023-06-27 21:04:19,644  - INFO - Logging into LinkedIn as digitalliqhtz@gmail.com...
2023-06-27 21:04:20,438  - INFO - Issues navigating landing page, attempt 1/3
2023-06-27 21:06:00,204  - INFO - Log in completed. Beginning to scrape jobs...
2023-06-27 21:06:55,124  - INFO - Currently scraping page 1 of 26 for machine learning engineer's with 635 results...
2023-06-27 21:41:04,640  - INFO - Done scraping page 1 of 26
2023-06-27 21:42:04,904  - INFO - Currently scraping page 2 of 25 for machine learning engineer's with 612 results...
2023-06-27 22:15:29,546  - INFO - Done scraping page 2 of 25
2023-06-27 22:16:21,291  - INFO - Currently scraping page 3 of 25 for machine learning engineer's with 621 results...
2023-06-27 22:49:38,286  - INFO - Done scraping page 3 of 25
2023-06-27 22:50:28,550  - INFO - Currently scraping page 4 of 26 for machine learning engineer's with 634 results...
2023-06-27 23:22:23,052  - INFO - Done scraping page 4 of 26
2023-06-27 23:23:26,083  - INFO - Currently scraping page 5 of 25 for machine learning engineer's with 613 results...
2023-06-27 23:56:26,553  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d97e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:26,555  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9660>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:26,557  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8c40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:36,569  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9ae0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:36,571  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9cf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:36,573  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9f00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:46,592  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0da410>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:46,594  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0da620>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:46,596  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0da830>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:56,606  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0da290>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:56,608  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9de0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:56:56,611  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9c30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:57:06,620  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d98a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:57:06,622  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9480>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:57:06,624  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:57:16,633  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dad40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:57:16,634  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0daf50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:57:16,635  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/element
2023-06-27 23:57:26,697  - INFO - Done scraping page 5 of 25
2023-06-27 23:57:26,699  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db940>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:26,700  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dbbb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:26,701  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dab60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:26,702  - ERROR - (1) Error while loading results for machine learning engineer on page 6 of 25, retrying...
2023-06-27 23:57:26,702  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db070>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:57:36,709  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:36,713  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dada0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:36,715  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8b20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:36,717  - ERROR - (2) Error remains for machine learning engineer. Moving to the next page...
2023-06-27 23:57:36,717  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8610>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:57:36,718  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:36,719  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9660>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:36,721  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9030>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:36,722  - ERROR - (1) Error while loading results for machine learning engineer on page 7 of 25, retrying...
2023-06-27 23:57:36,722  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d87c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:57:46,734  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9a80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:46,738  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9f00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:46,740  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0da0b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:46,741  - ERROR - (2) Error remains for machine learning engineer. Moving to the next page...
2023-06-27 23:57:46,742  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dbbe0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:57:46,743  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dbe50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:46,745  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128070>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:46,747  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:46,749  - ERROR - (1) Error while loading results for machine learning engineer on page 8 of 25, retrying...
2023-06-27 23:57:46,749  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dba90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:57:56,757  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9bd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:56,758  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9de0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:56,760  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8cd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:56,761  - ERROR - (2) Error remains for machine learning engineer. Moving to the next page...
2023-06-27 23:57:56,761  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9ae0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:57:56,764  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0da110>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:56,765  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8ac0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:56,767  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dab00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:57:56,768  - ERROR - (1) Error while loading results for machine learning engineer on page 9 of 25, retrying...
2023-06-27 23:57:56,768  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9150>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:58:06,773  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8790>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:06,776  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db0d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:06,778  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db130>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:06,780  - ERROR - (2) Error remains for machine learning engineer. Moving to the next page...
2023-06-27 23:58:06,780  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db340>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:58:06,782  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128340>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:06,784  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128520>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:06,786  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:06,788  - ERROR - (1) Error while loading results for machine learning engineer on page 10 of 25, retrying...
2023-06-27 23:58:06,788  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9e10>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:58:16,796  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:16,799  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dafb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:16,801  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d97e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:16,802  - ERROR - (2) Error remains for machine learning engineer. Moving to the next page...
2023-06-27 23:58:16,802  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dabc0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:58:16,805  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0da950>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:16,807  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d8df0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:16,809  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d86a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:16,811  - ERROR - (1) Error while loading results for machine learning engineer on page 11 of 25, retrying...
2023-06-27 23:58:16,812  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0db490>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:58:26,829  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9480>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:26,834  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9d20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:26,836  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0d9b70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:26,838  - ERROR - (2) Error remains for machine learning engineer. Moving to the next page...
2023-06-27 23:58:26,838  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b0dba90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2023-06-27 23:58:26,841  - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:26,842  - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b1289d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:26,843  - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128be0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/479eee321576ab966e58edcfbfded833/url
2023-06-27 23:58:26,846  - ERROR - (1) Error while loading results for machine learning engineer on page 12 of 25, retrying...
2023-06-27 23:58:26,846  - ERROR - HTTPConnectionPool(host='localhost', port=54532): Max retries exceeded with url: /session/479eee321576ab966e58edcfbfded833/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12b128df0>: Failed to establish a new connection: [Errno 61] Connection refused'))
